name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-badges:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: ${{ github.workspace }}
